a =  input    ('Имя')
b =  input    ('Отчество')
c =  input    ('Фамилия')
d =  input    ('Город')
f =  input    ('Возраст')
g =  input    ('Универститет')
h =  input    ('Факультет')
j =  input    ('Группа')
print ('Имя',a)
print ('Отчество',b)
print ('Фамилия',c)
print ('Город',d)
print ('Возраст',f)
print ('Университет',g)
print ('Факультет',h)
print ('Группа',j)